Option to switch units
saltysimulations/salty-747 pull request #140
Opened 2021-02-02 05:45 UTC by chloe1192

2021-02-24 11:27 UTC, 747-4EVER commented
Does this also change the fuel estimates on the Progress Page or are they still only in LBs?

2021-02-24 11:35 UTC, chloe1192 commented on html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_PerfInitPage.js
> +            }
I'm still trying to find a way to polish this. Some sim functions have the parameter "useLbs", and some use "unitIsMetric". I think adding both to the fmc var would be cleaner, maybe?

2021-02-24 11:55 UTC, chloe1192 commented
> 
> 
> Does this also change the fuel estimates on the Progress Page or are they still only in LBs?

Progress page will be more complicated i think.

2021-02-24 11:59 UTC, 747-4EVER commented
Yeah could be, I was just thinking about all the places that units are displayed from memory. Also there's the fuel flow gauges on the Engine EICAS page, I think they show KGs/hr by default.

2021-02-24 13:19 UTC, chloe1192 commented
> 
> 
> Yeah could be, I was just thinking about all the places that units are displayed from memory. Also there's the fuel flow gauges on the Engine EICAS page, I think they show KGs/hr by default.

I created a progress page, need to test if everything is working properly.

2021-02-26 02:13 UTC, zakiack commented
Name: zakiack#8247
Date of testing: Current date 25/2/2021
Version of the sim: Version the tester uses
PR Tested: #140 

Testing technique: Entered weight values in kg into the FMC, using the commits as a list of places to enter weights, switched them to lbs, and verified the accuracy of them by calculating in google. Then doing the same but from lbs to kg using different numbers
Steps you've made to test the Pull Request:
1. Powered on aircraft from cold and dark
2. Entered weight values into the FMC in kgs
3. Switched them to lbs
4. Verified them
5. Entered different weight values into fmc in lbs
6. Switched them to kgs
7. Verified them

Overall Rating: Good
Conclusions of the testing: Values are perfect
Only issue is in the menu to switch the values, the heading says ATIS SRC 
![Screenshot_539](https://user-images.githubusercontent.com/76414253/109245203-e8d3ec80-7794-11eb-8ed1-29eef0d9ebc4.png)

2021-02-26 06:28 UTC, ninjomcs commented
> Name: zakiack#8247
> Date of testing: Current date 25/2/2021
> Version of the sim: Version the tester uses
> PR Tested: #140
> 
> Testing technique: Entered weight values in kg into the FMC, using the commits as a list of places to enter weights, switched them to lbs, and verified the accuracy of them by calculating in google. Then doing the same but from lbs to kg using different numbers
> Steps you've made to test the Pull Request:
> 
> 1. Powered on aircraft from cold and dark
> 2. Entered weight values into the FMC in kgs
> 3. Switched them to lbs
> 4. Verified them
> 5. Entered different weight values into fmc in lbs
> 6. Switched them to kgs
> 7. Verified them
> 
> Overall Rating: Good
> Conclusions of the testing: Values are perfect
> Only issue is in the menu to switch the values, the heading says ATIS SRC
> ![Screenshot_539](https://user-images.githubusercontent.com/76414253/109245203-e8d3ec80-7794-11eb-8ed1-29eef0d9ebc4.png)

Did you also test the progress page? Did it work fine?

2021-02-26 17:46 UTC, zakiack commented
> Did you also test the progress page? Did it work fine?
 Yes, progress page works fine

2021-02-27 15:36 UTC, BobbyFuzzy commented
Name: BobbyFuzzy#4615
Date of testing: 27/20/2021
Version of the sim: 1.13.16.0
PR Tested: #140
Object of test: CDU

Testing technique: Setup flight & switch between units. Convert and check figures are converted properly.
Steps you've made to test the Pull Request:
1. Setup flight from cold and dark
2. Entered perf figures, switched units
3. Checked figures were correct by conversion
4. Started flight and checked progress page figures in the same manner

Flight notes:

- Everything OK on PERF INIT.
- Progress page seems to give me minus figures after converting to lbs whilst inflight, not sure if relevant as units would unlikely be changed in flight

![image](https://user-images.githubusercontent.com/5226010/109391888-49883400-7911-11eb-94ff-850b7830dd4c.png)

Issues (If Any): Mentioned above, may not be a concern
Overall Rating: Good
Conclusions of the testing: PR works as intended. Can switch between lbs and kgs successfully before setting up a flight.

2021-03-07 15:42 UTC, 747-4EVER commented
Name: 747-4EVER
Date of testing: 07/03/2021
Version of the sim: 1.13.16.0
PR Tested: #140
Object of test: CDU/Displays

Testing technique: Inspect displays on ground and in-flight while switching units.

Flight notes: N/A

Issues (If Any): 
- Fuel flow gauges on Engine EICAS page do not change their units. 
- Progress page is using old codebase not in line with latest dev build, should not be difficult to merge though. 
- Noticed that the fuel remaining at destination estimate was not accurate when in KGs (Its ok in LBS). See below image:

![image](https://user-images.githubusercontent.com/71572892/110245391-c5f6c480-7f5a-11eb-9dec-ee7d77614c7d.png)

ETA was approx 1.7 hours away at time of screenshot. With a fuel flow of 6TPH fuel burn to destination is 10.2T so estimate should be around 82, instead about 12 tonnes is missing.

Overall Rating: Good
Conclusions of the testing: Works mostly as intended, just needs small fixes for above issues.

2021-04-17 07:49 UTC, 747-4EVER requested changes
Was ready to merge, however compatibility seems to have been broken with latest sim update. The progress page no longer works and the fuel/engine EICAS page units don't change any more.

2021-04-19 18:42 UTC, merged