feat: fueling and boarding
saltysimulations/salty-747 pull request #339
Opened 2021-10-15 19:59 UTC by chloe1192

* Adds a convenient way to load fuel and payload via the CDU
* Adds a feature that saves the amount of fuel, so that the amount of fuel upon starting the next flight is whatever it was when the last flight ended.

![image](https://user-images.githubusercontent.com/26278705/184016290-882098e8-4fce-4bc2-8e0a-b6de61af7c5f.png)
![image](https://user-images.githubusercontent.com/26278705/184016325-641528f0-4859-4fb9-adc5-aaf7bc476d00.png)

**Testing instructions**
* Test the fueling and boarding features extensively, manually inputting values as well as importing from SimBrief, using both kg and lbs units. Make sure the fuel and weight is distributed in a reasonable way. Test out the different rate options. **Note: make sure to use the [new SimBrief airframe](https://www.simbrief.com/system/dispatch.php?sharefleet=141372_1660066082616).**

2021-12-10 02:44 UTC, DesertRick13 commented
If this happens, I hope there is an option for a 747-8F, BCF, and Passenger.

2022-01-10 03:52 UTC, iamdumdum1234 commented
Very cool!

2022-01-20 21:03 UTC, ninjomcs requested changes

2022-01-20 21:03 UTC, ninjomcs commented on salty-747/html_ui/Pages/Salty/SaltyStates.js
> +    }
cleaner to get rid of this if it's empty

2022-01-20 21:03 UTC, ninjomcs commented on salty-747/html_ui/Pages/Salty/SaltyStates.js
> +    }// ends update
same as above

2022-01-20 21:03 UTC, ninjomcs commented on salty-747/html_ui/Pages/VCockpit/Instruments/Airliners/B747_8/FMC/B747_8_FMC_Field.js
> +class FMC_Field {
what exactly is the purpose of this class / what does it do?

2022-02-14 05:27 UTC, giridat commented
Name: Giridhar Raut#5534
Date of testing: 14/02/2022
Version of the sim: Latest
PR Tested: #339 

Testing technique: Normal spawn C&D
Steps you've made to test the Pull Request:
1. Turn on acft go into boarding options 
2. Press FMC
3. FMC Comm > Boarding
4. Tested each page with different values and all at all the rates (Real, Fast, Instant)

Overall Rating: To be improved/ NOT PASS (check out the videos below)
Conclusions of the testing: 

1. The refueling option once started doesn't stop automatically after the refueling is complete whereas the other boarding options stop automatically.
2. I expect a 'Reset all Values to default' button which would reset the aircraft cargo and pax state to what it was upon spawning.
3. It would be feasible to know what unit KG or LBS is being used on the cargo page. 
4. I also want to know why the total PAX capacity is going to 364 whereas IRL it is 467?
5. The passenger page can be broken easily as the boarding rate for the pax page is on the previous Cargo page due to which if you change the rate on the cargo page which I believe changes the rate for the pax page as well sometimes doesn't happen video has been included for the same pax_page_behaviour.mp4.


https://user-images.githubusercontent.com/61822722/153805119-fe0faede-2673-4bc5-8ba0-7b535f3f5024.mp4


https://user-images.githubusercontent.com/61822722/153805131-007bbecf-6dd8-4cf7-b6b7-236b0062f5fc.mp4


https://user-images.githubusercontent.com/61822722/153805135-98c0e4ad-495b-40aa-aeaa-4a35d477446c.mp4



https://user-images.githubusercontent.com/61822722/153805326-30a59c80-9672-45f8-b3bd-28da7e5fb239.mp4

2022-08-10 20:49 UTC, ninjomcs approved these changes

2022-08-11 09:39 UTC, brewers10 commented
Name: brewers_10#5706
Date of testing:  11/08/2022
Version of the sim: Latest SU9 version
PR Tested: #339 

Testing technique: Loaded into the Salty 747 mod. Simbrief flight from YLRE --> YSSY created (units in KG to start) and loaded into the FMC. Loaded the route, fuel and payload all successfully and matching the values in the OFP. Switched units in FPL to LBS and also switched the units in the Salty 747 to LBS. Reloaded FPLN into the FMC and re-requested fuel and payload data aswell... all loaded in without any issues: very convenient. 
Steps you've made to test the Pull Request:
1. Loaded into YLRE in the Salty 747 (Salty Livery)
2. Loaded OFP into FMC
3. Requested Payload and Fuel figures from Simbrief
4. Loaded all payload and fuel onto the aircraft.
5. Repeated with units in LBS and also manually inputted figures to be loaded. No issues

Overall Rating: Good
Conclusions of the testing: It's hard to explain, but when requesting payload figures from Simbrief. The "Request send" button remains static, normally, when you request something the "Send" disappears whilst the aircraft retrieves data from Simbrief. If you need that explaining better contact me on Discord :)

2022-08-11 22:51 UTC, oz2010 commented
Name: oz2010#1558
Date of testing: 11/08/2022
Version of the sim: Latest SU9 version
PR Tested: https://github.com/saltysimulations/salty-747/pull/339

Testing technique: Load flight EDDF->KLAX, 316 pax 122.9k kg fuel ~6.3k kg payload. Try OFP request as well as manually setting all values. Messed around with the load speeds (fast/real/instant) to see how they work, also did some limits testing (details below)

Steps you've made to test the Pull Request:
1. Load flight as specified above
2. Do OFP request for the flight, start loading fuel and pax/cargo. Payload manager is able to handle both simultaneously as should be expected. Hit stop/start intermittently on both to check it stops and starts. Loading speed can be changed while stopped, and will resume at the new desired speed when started again.
3. Changed loading speed while loading, the effect is instant. Notable that changing to instant speed while loading will instantly finish.
4. Tried setting pax above the limit of 364, said "not allowed" as expected
5. Manually set desired fuel value to 0 and watched fuel tanks drain. Inner tanks drain first, followed by outer (as expected I believe). Then did OFP request again and filled back up to flight fuel
6. Tried higher values of fuel until it stopped letting me. The max appears to be 191.0k kg (technically 191.06 is the highest, which displays rounded as 191.1k kg). Interestingly, setting 191.1kg (or anything up to 191.19) shows "not allowed" on the scratchpad, but any higher values do not (instead just have no effect)


Overall Rating: Good
Conclusions: Great payload manager. Any issues are really small and nitpicky
1. For example, everything displays as "kg" but a way to show it's thousands of kg would be nice, but not strictly necessary (I recall the heavy division 787 does this too).
2. Cycling through the loading speeds is real->fast->instant->back to real, etc. ie no way to go backwards, so if you're trying to switch fast to real while actively loading you can't (it will instead switch to instant which instantly finishes). Not a big deal since the fix is just to stop, change speed to real by clicking twice, then start again - but it did catch me off guard while messing with stuff

Cheers to saying goodbye to the MSFS payload manager!

2022-08-12 22:20 UTC, ninjomcs approved these changes

2022-08-12 22:30 UTC, ninjomcs approved these changes

2022-08-13 16:37 UTC, Quantados commented
Name: Quantados#7632
Date of testing: Current date 13/08/2022
Version of the sim: SU10 Beta 3
PR Tested: #339 

Testing technique: Load into aircraft, loaded KSFO-KBOS route. Loaded fuel, payload, and route. Everything loaded correctly without any problems. 

Steps you've made to test the Pull Request:
1. Load into KSFO.
2. Requested OFP into fuel, payload, and route menus.
3. Changed Salty 747 units from LBS to KG a couple times.
4. Loaded fuel and payload.
5. Tried loading with real, fast, and instant rates.
6. Manually set fuel 10,000 lbs higher then tried draining it back to original.

Overall Rating: Good

Conclusions of the testing: 
Everything looked good. One small thing I saw was that SEL Fuel/SEL Cargo doesn't automatically convert when changing units in Salty 747.

2022-08-13 17:59 UTC, merged